import React, { useEffect, useMemo, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { AlertCircle, Loader2 } from 'lucide-react';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';
import { useCart } from '../context/CartContext';
import { formatCurrency } from '../utils/formatters';

const PAYMENTS = [['COD', 'Cash on Delivery'], ['UPI', 'UPI'], ['NETBANKING', 'Net Banking'], ['CARD', 'Card Payment']];

export default function CheckoutPlaceholderPage() {
  const { state } = useLocation(); const navigate = useNavigate(); const { currentUser } = useAuth(); const { cartItems, fetchCart } = useCart();
  const cartMode = state?.source === 'cart';
  const buyNow = !cartMode && state?.productId ? { productId: state.productId, quantity: state.quantity || 1 } : null;
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [placing, setPlacing] = useState(false);
  const [form, setForm] = useState({ name: currentUser?.username || '', contactNumber: currentUser?.phone || '', address: '', city: '', state: '', postalCode: '', paymentMethod: 'COD' });
  useEffect(() => { setForm((old) => ({ ...old, name: old.name || currentUser?.username || '', contactNumber: old.contactNumber || currentUser?.phone || '' })); }, [currentUser]);
  useEffect(() => {
    let mounted = true;
    (async () => { setLoading(true); setError(''); try {
      if (cartMode) { const latest = await fetchCart(); const values = latest?.items || cartItems; if (!values.length) throw new Error('Your cart is empty.'); if (mounted) setItems(values.map((item) => ({ productId: item.productId, productName: item.productName, price: Number(item.price), quantity: item.quantity, subtotal: Number(item.subtotal), invalid: !item.isActive || item.stock < item.quantity }))); }
      else if (buyNow) { const result = await api.get(`/products/${buyNow.productId}`); const product = (result.data || result).product; if (!product?.isActive || product.stock < buyNow.quantity) throw new Error('This product is no longer available in the selected quantity.'); if (mounted) setItems([{ productId: product.id, productName: product.name, price: Number(product.price), quantity: buyNow.quantity, subtotal: Number((Number(product.price) * buyNow.quantity).toFixed(2)), invalid: false }]); }
      else throw new Error('Start checkout through Buy Now or Buy All Cart.');
    } catch (err) { if (mounted) setError(err.message || 'Unable to prepare checkout.'); } finally { if (mounted) setLoading(false); } })();
    return () => { mounted = false; };
  }, [cartMode, buyNow?.productId, buyNow?.quantity]);
  const totals = useMemo(() => ({ products: items.length, quantity: items.reduce((n, item) => n + item.quantity, 0), amount: items.reduce((n, item) => n + item.subtotal, 0) }), [items]);
  const change = (event) => setForm((old) => ({ ...old, [event.target.name]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); if (items.some((item) => item.invalid)) return setError('A product changed availability. Refresh and review your checkout.'); setPlacing(true); setError(''); try { const response = await api.post('/orders', { source: cartMode ? 'cart' : 'buy_now', ...(cartMode ? {} : { items: [{ productId: buyNow.productId, quantity: buyNow.quantity }] }), shipping: { name: form.name, contactNumber: form.contactNumber, address: form.address, city: form.city, state: form.state, postalCode: form.postalCode }, paymentMethod: form.paymentMethod }); await fetchCart(); navigate('/order-confirmation', { replace: true, state: { order: (response.data || response).order } }); } catch (err) { setError(err.message || 'Order could not be placed.'); } finally { setPlacing(false); } };
  if (loading) return <div className="max-w-5xl mx-auto p-10 text-slate-400">Preparing checkout…</div>;
  if (!items.length) return <div className="max-w-2xl mx-auto p-10"><p className="text-rose-400">{error}</p><Link className="inline-block mt-5 text-blue-400" to="/products">Continue Shopping</Link></div>;
  return <form onSubmit={submit} className="max-w-5xl mx-auto px-4 py-10 grid lg:grid-cols-3 gap-7"><section className="lg:col-span-2 space-y-6"><div><p className="text-blue-400 text-sm font-semibold">Demo / Simulated Payment</p><h1 className="text-3xl font-extrabold">Checkout</h1><p className="text-slate-400">Final stock, prices, and totals are verified by the server.</p></div>{error && <p className="p-3 text-rose-400 border border-rose-500/30 rounded-xl flex gap-2"><AlertCircle className="w-5 h-5" />{error}</p>}<div className="p-5 bg-slate-800/50 border border-slate-700 rounded-2xl"><h2 className="font-bold mb-4">Shipping information</h2><div className="grid sm:grid-cols-2 gap-3">{[['name','Full name'],['contactNumber','Contact number'],['address','Address'],['city','City'],['state','State'],['postalCode','Postal code']].map(([name,label]) => <label key={name} className={name === 'address' ? 'sm:col-span-2' : ''}><span className="text-xs text-slate-400">{label}</span><input required name={name} value={form[name]} onChange={change} className="mt-1 w-full p-2.5 bg-slate-900 border border-slate-700 rounded-lg" /></label>)}</div></div><div className="p-5 bg-slate-800/50 border border-slate-700 rounded-2xl"><h2 className="font-bold">Payment method</h2><p className="text-xs text-amber-300 my-3">Demo only — never enter card, UPI, PIN, or bank credentials.</p>{PAYMENTS.map(([value,label]) => <label key={value} className="flex gap-3 p-3 mb-2 border border-slate-700 rounded-xl"><input type="radio" name="paymentMethod" value={value} checked={form.paymentMethod === value} onChange={change} /><span>{label}<small className="block text-slate-400">{value === 'COD' ? 'Payment status: Pending' : 'Payment status: Paid (simulated)'}</small></span></label>)}</div></section><aside className="p-5 bg-slate-800/50 border border-slate-700 rounded-2xl h-fit sticky top-24"><h2 className="font-bold">Order summary</h2><p className="mt-2 text-xs text-slate-500">Invoice: assigned securely when placed</p><p className="text-xs text-slate-500">Order Date: {new Date().toLocaleDateString()}</p>{items.map((item) => <div className="py-3 border-b border-slate-700 text-sm" key={item.productId}><b>{item.productName}</b><br /><span className="text-slate-400">{item.quantity} × {formatCurrency(item.price)}</span><span className="float-right">{formatCurrency(item.subtotal)}</span></div>)}<div className="mt-4 text-sm space-y-1"><p>Total Products: <b>{totals.products}</b></p><p>Total Quantity: <b>{totals.quantity}</b></p><p className="text-lg font-bold">Total Amount: {formatCurrency(totals.amount)}</p><p>Payment Status: <b>{form.paymentMethod === 'COD' ? 'Pending' : 'Paid (simulated)'}</b></p></div><button disabled={placing} className="w-full mt-5 p-3 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 rounded-xl font-semibold">{placing ? <span className="flex justify-center gap-2"><Loader2 className="w-5 animate-spin" />Placing Order…</span> : 'Place Order'}</button></aside></form>;
}
