import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';

export default function ProfilePage() {
  const navigate = useNavigate(); const { logout, updateCurrentUser } = useAuth();
  const [form, setForm] = useState({ username: '', email: '', phone: '' }); const [password, setPassword] = useState({ currentPassword: '', newPassword: '', confirmNewPassword: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [confirmingDelete, setConfirmingDelete] = useState(false);
  useEffect(() => { api.get('/users/me').then((res) => { const user = (res.data || res).user; setForm({ username: user.username, email: user.email, phone: user.phone }); }).catch((err) => setError(err.message)); }, []);
  const change = (setter) => (event) => setter((old) => ({ ...old, [event.target.name]: event.target.value }));
  const saveProfile = async (event) => { event.preventDefault(); setBusy(true); setError(''); setMessage(''); try { const res = await api.put('/users/me', form); const user = (res.data || res).user; updateCurrentUser(user); setMessage('Profile updated successfully.'); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const savePassword = async (event) => { event.preventDefault(); setBusy(true); setError(''); setMessage(''); try { await api.put('/users/me/password', password); logout(); navigate('/login', { replace: true }); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const deleteAccount = async () => { setBusy(true); setError(''); try { await api.delete('/users/me'); logout(); navigate('/login', { replace: true }); } catch (err) { setError(err.message); setBusy(false); } };
  return <div className="max-w-3xl mx-auto px-4 py-10 space-y-6"><div><h1 className="text-3xl font-extrabold">My Profile</h1><p className="text-slate-400">Manage your account information securely.</p></div>{error && <p className="p-3 text-rose-400 border border-rose-500/30 rounded-xl">{error}</p>}{message && <p className="p-3 text-emerald-400 border border-emerald-500/30 rounded-xl">{message}</p>}<form onSubmit={saveProfile} className="p-5 bg-slate-800/50 border border-slate-700 rounded-2xl space-y-3"><h2 className="font-bold text-lg">Account information</h2>{[['username','Username'],['email','Email'],['phone','Contact number']].map(([name,label]) => <label key={name} className="block"><span className="text-xs text-slate-400">{label}</span><input required name={name} value={form[name]} onChange={change(setForm)} className="mt-1 w-full p-2.5 rounded-lg bg-slate-900 border border-slate-700" /></label>)}<p className="text-sm text-slate-400">Password: ••••••••</p><button disabled={busy} className="px-4 py-2 bg-blue-600 rounded-lg disabled:opacity-50">Save Changes</button></form><form onSubmit={savePassword} className="p-5 bg-slate-800/50 border border-slate-700 rounded-2xl space-y-3"><h2 className="font-bold text-lg">Change Password</h2>{[['currentPassword','Current password'],['newPassword','New password'],['confirmNewPassword','Confirm new password']].map(([name,label]) => <label key={name} className="block"><span className="text-xs text-slate-400">{label}</span><input required type="password" name={name} value={password[name]} onChange={change(setPassword)} className="mt-1 w-full p-2.5 rounded-lg bg-slate-900 border border-slate-700" /></label>)}<button disabled={busy} className="px-4 py-2 bg-indigo-600 rounded-lg disabled:opacity-50">Change Password</button><p className="text-xs text-slate-400">Changing your password signs you out of all existing sessions.</p></form><section className="p-5 border border-rose-500/40 bg-rose-950/20 rounded-2xl"><h2 className="font-bold text-rose-300">Delete Account</h2><p className="my-2 text-sm text-slate-400">Historical orders are retained; your account is deactivated and your cart is cleared.</p>{!confirmingDelete ? <button onClick={() => setConfirmingDelete(true)} className="px-4 py-2 border border-rose-500 text-rose-300 rounded-lg">Delete Account</button> : <div className="mt-3"><p className="font-semibold text-rose-300">Are you sure you want to permanently delete your account?</p><button onClick={deleteAccount} disabled={busy} className="mt-3 px-4 py-2 bg-rose-600 rounded-lg">Yes, Delete Account</button><button onClick={() => setConfirmingDelete(false)} className="ml-3 px-4 py-2 bg-slate-700 rounded-lg">Cancel</button></div>}</section></div>;
}
