import React, { useEffect, useState } from 'react';
import { CreditCard, ShieldCheck } from 'lucide-react';
import api from '../../services/api';
import AdminNav from '../../components/AdminNav';
import { formatCurrency } from '../../utils/formatters';

export default function AdminPaymentsPage() {
  const [payments, setPayments] = useState([]); const [error, setError] = useState('');
  useEffect(() => { api.get('/admin/payments').then((res) => setPayments((res.data || res).payments || [])).catch((err) => setError(err.message || 'Unable to load payments.')); }, []);
  return <div className="mx-auto w-full max-w-7xl flex-1 px-4 py-8 sm:px-6 lg:px-8"><AdminNav /><div className="mb-6"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-300">Simulated settlement ledger</p><h1 className="mt-2 flex items-center gap-3 text-3xl font-extrabold"><CreditCard className="h-8 w-8 text-emerald-300" />Payments</h1><p className="mt-2 text-sm text-slate-400">Only persisted simulated payment metadata is shown. No card, CVV, PIN, or bank credentials are collected.</p></div>{error && <p className="mb-4 rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-300">{error}</p>}<div className="overflow-hidden rounded-2xl border border-slate-700/70 bg-slate-800/50 shadow-xl"><div className="flex items-center gap-2 border-b border-slate-700/60 p-4 text-xs text-slate-400"><ShieldCheck className="h-4 w-4 text-emerald-300" />Simulated payment records only</div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-900/60 text-xs uppercase tracking-wider text-slate-400"><tr><th className="p-4">Invoice</th><th className="p-4">Customer</th><th className="p-4">Amount</th><th className="p-4">Method</th><th className="p-4">Payment status</th><th className="p-4">Order status</th><th className="p-4">Date</th></tr></thead><tbody className="divide-y divide-slate-700/60">{payments.map((payment) => <tr key={payment.invoiceNumber}><td className="p-4 font-semibold text-white">{payment.invoiceNumber}</td><td className="p-4 text-slate-300">{payment.customer}</td><td className="p-4 font-semibold text-white">{formatCurrency(payment.amount)}</td><td className="p-4 text-slate-300">{payment.paymentMethod}</td><td className="p-4 text-slate-300">{payment.paymentStatus}</td><td className="p-4 text-slate-300">{payment.orderStatus}</td><td className="p-4 text-xs text-slate-400">{new Date(payment.date).toLocaleString()}</td></tr>)}</tbody></table>{!payments.length && <p className="p-10 text-slate-400">No payment records found.</p>}</div></div></div>;
}
