import React, { useEffect, useState } from 'react';
import { ShieldCheck, UserRound } from 'lucide-react';
import api from '../../services/api';
import AdminNav from '../../components/AdminNav';

export default function AdminUsersPage() {
  const [users, setUsers] = useState([]); const [error, setError] = useState('');
  useEffect(() => { api.get('/admin/users').then((res) => setUsers((res.data || res).users || [])).catch((err) => setError(err.message || 'Unable to load users.')); }, []);
  return <div className="mx-auto w-full max-w-7xl flex-1 px-4 py-8 sm:px-6 lg:px-8"><AdminNav /><div className="mb-6"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Customer directory</p><h1 className="mt-2 flex items-center gap-3 text-3xl font-extrabold"><UserRound className="h-8 w-8 text-cyan-300" />Users</h1><p className="mt-2 text-sm text-slate-400">Account contact and status data only. Authentication secrets are never returned.</p></div>{error && <p className="mb-4 rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-300">{error}</p>}<div className="overflow-hidden rounded-2xl border border-slate-700/70 bg-slate-800/50 shadow-xl"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-900/60 text-xs uppercase tracking-wider text-slate-400"><tr><th className="p-4">Username</th><th className="p-4">Email</th><th className="p-4">Contact</th><th className="p-4">Role</th><th className="p-4">Registered</th><th className="p-4">Status</th></tr></thead><tbody className="divide-y divide-slate-700/60">{users.map((user) => <tr key={user.id}><td className="p-4 font-semibold text-white">{user.username}</td><td className="p-4 text-slate-300">{user.email}</td><td className="p-4 text-slate-300">{user.phone}</td><td className="p-4"><span className="inline-flex items-center gap-1 text-xs text-amber-300"><ShieldCheck className="h-3.5 w-3.5" />{user.role}</span></td><td className="p-4 text-xs text-slate-400">{new Date(user.registrationDate).toLocaleString()}</td><td className="p-4"><span className={user.status === 'ACTIVE' ? 'text-xs font-semibold text-emerald-300' : 'text-xs font-semibold text-slate-500'}>{user.status}</span></td></tr>)}</tbody></table>{!users.length && <p className="p-10 text-slate-400">No users found.</p>}</div></div></div>;
}
